### ISSUE TITLE
Add a way to wait until changes are synchronized with fission

### ISSUE THREAD

**Issue by matheus23** [oddsdk/ts-odd#187]
# Summary

I want to have a way to be notified until a `.publish()` call finally finishes synchronized the changes with the fission servers. I.e. to get notified when the "🪴 DNSLink updated: ..." message appears in the console after a publish call.

## Problem

There is no API for that. There exists `webnative.dataRoot.update`, but it's not possible to use this API in conjunction with the FileSystem's `publish`: Publish will always call `dataRoot.update` without exposing the actual promise that does the work to the user.

### Impact

In my UI I can't indicate to the user when a publish is in-progress. I have no way of figuring out when it's done.

## Solution

I'm not sure. One way would be an option to turn off dataRoot updating in file systems.

**Comment by icidasset** [comment]
Implemented on `next` branch.
