### ISSUE TITLE
Pointilistic Private Partition UCAN Capabilities

### ISSUE THREAD

**Issue by expede** [oddsdk/ts-odd#313]
We have this written in detail... somewhere. I'll dig it up. In the meantime:

Currently UCANs include the entire bare namefilter. This is both space inefficient, and leaks more information than it strictly needs to. We're doubling the size of namefilters (#312) to solve related challenges, but that makes the space problem worse.

The optimization is to list only the hash of the current highest directory that you're given access to. This operates recursively, so if the parent UCAN has hash A, and the child UCAN has hash B, then you must have both in the filter. This moves us from a straight line bare namefilter to a pointalistic view.

Multiple hashes may eventually be required per layer (`AND`ed), but the belief right now is that it won't be necessary, so putting that off.

**Comment by matheus23** [comment]
> Currently UCANs include the entire bare namefilter.

I think that's not the case right now:
![image](https://user-images.githubusercontent.com/1430958/141149651-bcdfa2d0-c7c8-405e-8ebb-ff1753b7b88d.png)


These are the 3 UCANs from my drive.fission.codes.

Apparently, `fct: []`. Perhaps that's a bug?

**Comment by matheus23** [comment]
> > Apparently, fct: []. Perhaps that's a bug?
> 
> fct: [] can be omitted, but it's not a semantic bug I guess

Hm. I'm trying to understand what the system should look like. Above you say

> Currently UCANs include the entire bare namefilter

But I can't find where that bare namefilter *is* in my ucans. I thought it should be in the `fct` field, and I thought, maybe it's a bug that it's not in there?
