### ISSUE TITLE
Don't generate `AES-CTR` webcrypto keys

### ISSUE THREAD

**Issue by matheus23** [oddsdk/ts-odd#488]
# Summary

Generating AES-CTR keys causes Safari to print a warning to the console that this is not safe. Safari is right, an authenticated cipher should be preferred.
However, we actually *do* prefer an authenticated cipher! We use AES-GCM. So why does the warning get printed?
Well, because we essentially do this (pseudocode):
```ts
const key = webcrypto.generateKey("AES-CTR") // safari prints a warning accordingly
const keyBytes = webcrypto.exportKey(key)
// key gets stored/passed around like that and then later
const importedKey = webcrypto.importKey("AES-GCM", keyBytes)
// on encryption we use this
webcrypto.encrypt("AES-GCM", importedKey, data)
```

## Problem

We shouldn't generate AES-CTR keys. We also have a constant:

https://github.com/fission-codes/webnative/blob/0e3224706f6565b29e327d7392b88b0e804e5f99/src/fs/protocol/basic.ts#L19

which should definitely either be removed or set to AES-GCM.

### Impact

* Safari users get a scary warning printed on the console
* Future development may accidentally make use of AES-CTR in an unsafe way

## Solution

Either
* change the constant to AES-GCM or
* delete the constant, as it's not actually useful.

# Detail

We could delete the constant and replace use sites like this:

https://github.com/fission-codes/webnative/blob/0e3224706f6565b29e327d7392b88b0e804e5f99/src/fs/v1/PrivateTree.ts#L189

With code like this:

```ts
import { webcrypto } from "one-webcrypto"

const key = webcrypto.getRandomValues(new Uint8Array(32))
```

**Comment by icidasset** [comment]
Fixed on `next` branch.
