### ISSUE TITLE
Fix offline support

### ISSUE THREAD

**Issue by mjamesderocher** [oddsdk/ts-odd#498]
# Summary

Offline support in recent version of Webnative is not working.

## Problem

When trying to run a site using Webnative, the console shows the errors:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cloudflare-dns.com/dns-query?name=_did.zsktgjmutuo5bs24o72abcas6b4zkocw.fission.name&type=txt. (Reason: CORS request did not succeed). Status code: (null).`

and

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://dns.google/resolve?name=_did.zsktgjmutuo5bs24o72abcas6b4zkocw.fission.name&type=txt. (Reason: CORS request did not succeed). Status code: (null).`

These calls come from the file lib/components/reference/dns-over-https.ts

The issue only shows up if the filesystem is set to `loadImmediately: true` when initiating the program.

**Comment by icidasset** [comment]
Fixed on `next` branch. We'll be doing a new release soon(ish) 👀
