### ISSUE TITLE
Create file system before account registration

### ISSUE THREAD

**Issue by bgins** [oddsdk/ts-odd#518]
# Summary

## Problem

Users need to create an account to access the file system.

### Impact

It challenging for developers to create apps that use local-only file systems.

## Solution

Always create a file system, even before the user registers an account. An app can use the file system in local-only mode before an account is created, which would mean the file system is not published. When a user creates an account, start publishing the file system.

Note that there is some overlap here with https://github.com/oddsdk/ts-odd/issues/475, but the convenience method for temporary file systems may be useful for creating multiple file systems.

**Comment by icidasset** [comment]
Implemented on `next` branch.
