### ISSUE TITLE
exporting private keys 

### ISSUE THREAD

**Issue by gotjoshua** [oddsdk/ts-odd#530]
# Summary
I want to use odd for auth and creating crypto keys. but i see that the private keys are not exportable, and the mnemonic is never made available.

## Problem
If a user encrypts data and then clears local storage, the data is gone.

### Impact
Data loss.

## Solution
make this extractable = true (should save 1 char of code ; )
![image](https://github.com/oddsdk/ts-odd/assets/8686454/607c9708-9970-430b-bd2f-186262eeb8aa)

# Detail

**Describe alternatives you've considered**
making new keys instead of the default exchange key that odd crypto creates

**Comment by matheus23** [comment]
Asymmetric keys are intentionally non-extractable. This is safer in the event of temporary device compromises: It allows us to rotate the keys that are encrypted *for* the exchange key, without having to rotate the exchange key itself (as it's not compromised). This could happen e.g. when someone downloads a malicious extension, but then removes it again, or there's a javascript supply chain attack on an ODD app.

What we do for recovery in the [dashboard](https://github.com/fission-codes/dashboard/) is read out the root symmetric key for a directory. That allows us to recover the filesystem data as long as the key hasn't been rotated.
However, if I had to re-design that today, I'd instead create a new extractable key pair and write out the mnemonic, so the user can make note of it, and finally delete the private portion in the browser.
This way, the recovery kit ("backup") acts like "another device" that has access. It can receive key rotation updates and be revoked like other devices (stop receiving key rotation updates) as well.

**Comment by gotjoshua** [comment]
> I'd instead create a new extractable key pair and write out the mnemonic, so the user can make note of it, and finally delete the private portion in the browser.

if by "private portion" you mean the extractable from the browser, then that's exactly what i was thinking. and i guess if you all don't implement it, i will need to do it in parallel (or instead) of using your keys...

**Comment by matheus23** [comment]
Yes exactly.

It should be possible to do this in parallel to using our keys.

**Comment by icidasset** [comment]
@gotjoshua You can write your own crypto component for the SDK to adjust the behaviour to your needs if you want to experiment.

You would pass an object to `program(crypto: obj)` of this type:
https://github.com/oddsdk/ts-odd/blob/db89623bbab458ccfdfa673b5e0804e36a1e3e7a/src/components/crypto/implementation.ts#L14

See here for the default implementation:
https://github.com/oddsdk/ts-odd/blob/db89623bbab458ccfdfa673b5e0804e36a1e3e7a/src/components/crypto/implementation/browser.ts#L307

I think when initialising the keystore you could create key pairs that are exportable, and when needing the key pairs (as in `ksPublicWriteKey`) you just fetch those instead. That would be one way of doing it. You could also not use keystore-idb at all.

**Comment by gotjoshua** [comment]
> in parallel to using our keys.

yeah, i gotta work out which keys are most appropriate for which parts...

thanks for your support and engagement @icidasset  and @matheus23
