### ISSUE TITLE
lodash imports from bloom-filters not tree shaking

### ISSUE THREAD

**Issue by gotjoshua** [oddsdk/ts-odd#559]
```
dependencies:
@oddjs/odd 0.37.2
└─┬ fission-bloom-filters 1.7.1
  └── lodash 4.17.21
```
bloom filters doesn't have issues enabled so I'll post this here.

https://www.npmjs.com/package/lodash-es  
https://lodash.com/per-method-packages  

I noticed that odd is responsible for quite a bit of node modules bloat. 
lodash may be an easy fix, as you are using several different import methods some from individual packages, and some from the whole shebang...

![image](https://github.com/oddsdk/ts-odd/assets/8686454/45c884cc-4c8f-4b8e-8a3f-f68144da4bfa)

**Comment by icidasset** [comment]
Thanks for looking at that, we definitely want to reduce this as much as possible. Bloom filters pkg should be removed in the next iteration of the SDK (see `next` branch). We’ve also leaned a bit more into the component aspect so you’re not adding everything to the js bundle. Sadly it does still end up in your node modules.

**Comment by gotjoshua** [comment]
no worries about the node modules directory for me... just the actual bundle sizes that i'm concerned about.

i'm also trying to find new ways to think about bundles and cdn within the web3 ecosystem. seems like many projects are rebundling noble curves, multiformats, nacl, buffer etc... ( so they end up in the bundle multiple times)

feels like there must be a better way, maybe peer deps? or an ecosystem convention to load a meta lib from cdn... i dunno.

**Comment by icidasset** [comment]
👌 Bundle size will be better in the upcoming release. Maybe the next step is to split it up in multiple packages 🤔 

Peer deps could be an option yeah. Although handling version inconsistencies with things like multiformats is not fun. At some point we even had inconsistencies with different CID classes in the SDK itself 😅 Also, hopefully more things get added to the Web Crypto API so noble curve libraries aren't needed.

**Comment by gotjoshua** [comment]
> handling version inconsistencies with things like multiformats

ouch.



> Bundle size will be better in the upcoming release.

amazing! looking forward to the changelog also....
